---
openapi: 3.0.2
info:
  title: Cloud Fast
  version: 0.1.0

x-tagGroups:
  - name: Network
    tags:
      - create
      - delete
  - name: User Management
    tags:
      - user
info:
  description: | This is a CloudFast API documentation |
paths:
  "/create_vpc":
    post:
      summary: Create Vpc
      operationId: create_vpc_create_vpc_post
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
  "/delete_vpc/{vpc_id}":
    delete:
      summary: Delete Vpc
      operationId: delete_vpc_delete_vpc__vpc_id__delete
      parameters:
        - required: true
          schema:
            title: Vpc Id
            type: string
          name: vpc_id
          in: path
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
